
from types import SimpleNamespace


# 定义参数，使用 SimpleNamespace 方便访问
params_mpp_Ti = SimpleNamespace(
    log_to_wandb=True,
    log_to_screen=True,
    save_checkpoint=True,
    checkpoint_save_interval=10,
    debug_grad=True,
    true_time=False,
    num_data_workers=6,
    enable_amp=False,
    compile=False,
    gradient_checkpointing=False,
    exp_dir='~/MPP',
    log_interval=1,
    pretrained=False,
    project='project', 
    group='debugging',
    entity='entity',
    drop_path=0.4,
    max_epochs=500,
    scheduler_epochs=-1,
    epoch_size=150,
    rescale_gradients=False,
    optimizer='adam',
    scheduler='cosine',
    warmup_steps=1000,
    learning_rate=5e-4,
    weight_decay=1e-3,
    n_states=12,
    state_names=['Pressure', 'Vx', 'Vy', 'Density', 'Vx', 'Vy', 'Density', 'Pressure'],
    dt=1,
    n_steps=16,
    enforce_max_steps=False,
    accum_grad=5,
    model_type='avit',
    block_type='axial',
    time_type='attention',
    space_type='axial_attention',
    tie_fields=False,
    embed_dim=192,
    num_heads=3,
    processor_blocks=12,
    patch_size=[16, 16],
    bias_type='rel',
    train_val_test=[.8, .1, .1],
    augmentation=False,
    use_all_fields=True,
    tie_batches=False,
    extended_names=False,
    embedding_offset=0,
    train_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    valid_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    append_datasets=[]
)


params_mpp_S = SimpleNamespace(
    log_to_wandb=True,
    log_to_screen=True,
    save_checkpoint=True,
    checkpoint_save_interval=10,
    debug_grad=True,
    true_time=False,
    num_data_workers=6,
    enable_amp=False,
    compile=False,
    gradient_checkpointing=False,
    exp_dir='~/MPP',
    log_interval=1,
    pretrained=False,
    project='project', 
    group='debugging',
    entity='entity',
    drop_path=0.1,
    max_epochs=500,
    scheduler_epochs=-1,
    epoch_size=150,
    rescale_gradients=False,
    optimizer='adam',
    scheduler='cosine',
    warmup_steps=1000,
    learning_rate=5e-4,
    weight_decay=1e-3,
    n_states=12,
    state_names=['Pressure', 'Vx', 'Vy', 'Density', 'Vx', 'Vy', 'Density', 'Pressure'],
    dt=1,
    n_steps=80,
    enforce_max_steps=False,
    accum_grad=5,
    model_type='avit',
    block_type='axial',
    time_type='attention',
    space_type='axial_attention',
    tie_fields=False,
    embed_dim=384,
    num_heads=6,
    processor_blocks=12,
    patch_size=[16, 16],
    bias_type='rel',
    train_val_test=[.8, .1, .1],
    augmentation=False,
    use_all_fields=True,
    tie_batches=False,
    extended_names=False,
    embedding_offset=0,
    train_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    valid_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    append_datasets=[]
)


params_mpp_B = SimpleNamespace(
    log_to_wandb=True,
    log_to_screen=True,
    save_checkpoint=True,
    checkpoint_save_interval=10,
    debug_grad=True,
    true_time=False,
    num_data_workers=6,
    enable_amp=False,
    compile=False,
    gradient_checkpointing=False,
    exp_dir='~/MPP',
    log_interval=1,
    pretrained=False,
    project='project', 
    group='debugging',
    entity='entity',
    drop_path=0.1,
    max_epochs=500,
    scheduler_epochs=-1,
    epoch_size=150,
    rescale_gradients=False,
    optimizer='adam',
    scheduler='cosine',
    warmup_steps=1000,
    learning_rate=5e-4,
    weight_decay=1e-3,
    n_states=12,
    state_names=['Pressure', 'Vx', 'Vy', 'Density', 'Vx', 'Vy', 'Density', 'Pressure'],
    dt=1,
    n_steps=80,
    enforce_max_steps=False,
    accum_grad=5,
    model_type='avit',
    block_type='axial',
    time_type='attention',
    space_type='axial_attention',
    tie_fields=False,
    embed_dim=768,
    num_heads=12,
    processor_blocks=12,
    patch_size=[16, 16],
    bias_type='rel',
    train_val_test=[.8, .1, .1],
    augmentation=False,
    use_all_fields=True,
    tie_batches=False,
    extended_names=False,
    embedding_offset=0,
    train_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    valid_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    append_datasets=[]
)


params_mpp_L = SimpleNamespace(
    log_to_wandb=True,
    log_to_screen=True,
    save_checkpoint=True,
    checkpoint_save_interval=10,
    debug_grad=True,
    true_time=False,
    num_data_workers=6,
    enable_amp=False,
    compile=False,
    gradient_checkpointing=False,
    exp_dir='~/MPP',
    log_interval=1,
    pretrained=False,
    project='project', 
    group='debugging',
    entity='entity',
    drop_path=0.1,
    max_epochs=500,
    scheduler_epochs=-1,
    epoch_size=150,
    rescale_gradients=False,
    optimizer='adam',
    scheduler='cosine',
    warmup_steps=1000,
    learning_rate=5e-4,
    weight_decay=1e-3,
    n_states=12,
    state_names=['Pressure', 'Vx', 'Vy', 'Density', 'Vx', 'Vy', 'Density', 'Pressure'],
    dt=1,
    n_steps=80,
    enforce_max_steps=False,
    accum_grad=5,
    model_type='avit',
    block_type='axial',
    time_type='attention',
    space_type='axial_attention',
    tie_fields=False,
    embed_dim=1024,
    num_heads=16,
    processor_blocks=24,
    patch_size=[16, 16],
    bias_type='rel',
    train_val_test=[.8, .1, .1],
    augmentation=False,
    use_all_fields=True,
    tie_batches=False,
    extended_names=False,
    embedding_offset=0,
    train_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    valid_data_paths=[
        ['~/PDEBench/2D/shallow-water', 'swe', ''],
        ['~/PDEBench/2D/NS_incom', 'incompNS', ''],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '128'],
        ['~/PDEBench/2D/CFD/2D_Train_Rand', 'compNS', '512'],
        ['~/PDEBench/2D/CFD/2D_Train_Turb', 'compNS', ''],
        ['~/PDEBench/2D/diffusion-reaction', 'diffre2d', ''],
    ],
    append_datasets=[]
)

